### ISSUE TITLE
Issue that might relate to dependencies

### ISSUE THREAD

**Issue by kmaasrud** [toshism/org-super-links#16]
When inserting a link with `sl-link`, I'm greeted with this message:

```
Symbol's value as variable is void: helm-org-ql-actions
```

I suspect this has something to do with org-ql and helm-org, but both are installed and working. Do you have an idea on why this is happening and how to solve it?

**Comment by toshism** [comment]
Yes, this was a bug and was recently fixed in the develop branch. You can see #14 for more details. 

I will create a new release soon, but you can also switch to the develop branch until then.

**Comment by toshism** [comment]
I'm going to close this but feel free to reopen if you still see this issue on the develop branch.

Thanks!

**Comment by kmaasrud** [comment]
I've switched to the develop branch and loaded the bug fix, but still no luck... Everything else works well, but as soon as I'm trying to use helm with `sl-link`, it tells me the same
